In [5]:
import numpy as np

In [7]:
john = np.array([4, 60, 59])

In [8]:
loves = np.array([10, 100, 20])

In [9]:
mary = np.array([0, 10, 22])

In [10]:
john + loves + mary

array([ 14, 170, 101])

In [11]:
john * loves * mary

array([    0, 60000, 25960])

In [18]:
loves_kron = np.kron(loves, loves).reshape(3, 3)
loves_kron

array([[  100,  1000,   200],
       [ 1000, 10000,  2000],
       [  200,  2000,   400]])

In [19]:
john_mary = np.kron(john, mary).reshape(3, 3)
john_mary

array([[   0,   40,   88],
       [   0,  600, 1320],
       [   0,  590, 1298]])

In [20]:
loves_kron * john_mary

array([[      0,   40000,   17600],
       [      0, 6000000, 2640000],
       [      0, 1180000,  519200]])

In [24]:
loves_cat = loves_kron + np.kron([2, 36, 19], loves).reshape(3, 3) + np.kron([19, 7, 3], mary).reshape(3, 3)
loves_cat

array([[  120,  1390,   658],
       [ 1360, 13670,  2874],
       [  390,  3930,   846]])

In [25]:
loves_cat * john_mary

array([[      0,   55600,   57904],
       [      0, 8202000, 3793680],
       [      0, 2318700, 1098108]])

In [27]:
loves_cat.dot(mary)

array([ 28376, 199928,  57912])

In [45]:
john_loves_mary__copy_obj = john * loves_cat.dot(mary)
john_loves_mary__copy_obj

array([  113504, 11995680,  3416808])

In [40]:
np.array(
    [
        [1, 2, 3],
        [10, 20, 30]
    ]).dot(
    np.array([[1, 2, 1]]).T
)

array([[ 8],
       [80]])

In [42]:
loves_cat.T

array([[  120,  1360,   390],
       [ 1390, 13670,  3930],
       [  658,  2874,   846]])

In [43]:
loves_cat.T.dot(john)

array([ 105090, 1057630,  224986])

In [46]:
john_loves_mary__copy_subj = mary * loves_cat.T.dot(john)
john_loves_mary__copy_subj

array([       0, 10576300,  4949692])

In [47]:
john_loves_mary__copy_obj + john_loves_mary__copy_subj

array([  113504, 22571980,  8366500])

In [50]:
np.kron(john_loves_mary__copy_obj, john_loves_mary__copy_subj).reshape(3, 3)

array([[              0,   1200452355200,    561809840768],
       [              0, 126869910384000,  59374921330560],
       [              0,  36137186450400,  16912147223136]])